
version: '3.3'
services:
 web:
  build:
    context: ./php
    dockerfile: Dockerfile
  container_name: php73
  networks:
    - backend
  volumes:
    - ./php:/var/www/html/
  ports:
    - 8000:80
 db:
  container_name: mysql8
  image: mysql:8.0
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment: 
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: test_db
   MYSQL_USER: devuser
   MYSQL_PASSWORD: devpass
  ports:
    - 3306:3306
  networks:
   - backend
 dbteste:
  image: phpmyadmin/phpmyadmin:latest
  ports:
   - 8001:80
  environment:
   - PMA_ARBITRARY=1
  networks:
   - backend
  

networks:
  backend:
    driver: "bridge"